name: Docker push google-photos-scraper on Github registry

on:
  push:
    branches:
      - master
    paths:
      - scraper/google-photos/*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Image
        uses: matootie/github-docker@v3.0.0
        with:
          accessToken: ${{ github.token }}
          imageName: google-photos
          tag: 0.0.1
          context: scraper/google-photos
