name: Docker push tor on Github registry

on:
  push:
    branches:
      - master
    paths:
      - tor/*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Image
        uses: matootie/github-docker@v3.0.0
        with:
          accessToken: ${{ github.token }}
          imageName: tor
          tag: 0.0.1
          context: tor
