name: Docker push yggdrasil on Github registry

on:
  push:
    branches:
      - master
    paths:
      - Yggdrasil/*
defaults:
  run:
    shell: bash
    working-directory: Yggdrasil

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Image
        uses: matootie/github-docker@v3.0.0
        with:
          accessToken: ${{ github.token }}
          imageName: yggdrasil
          tag: 0.0.1
