name: Docker push yggdrasil on Github registry

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Yggdrasil/*
defaults:
  run:
    shell: bash
    working-directory: Yggdrasil

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Publish Image
        uses: matootie/github-docker@v3.0.0
        with:
          accessToken: ${{ github.token }}
          imageName: yggdrasil
          tag: 0.0.1
          context: Yggdrasil
      - name: Deploy
        if: success()
        uses: yuyitech/github-action-rancher2@v0.0.1
        env:
          RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_ACCESS_KEY }}
          RANCHER_SECRET_KEY: ${{ secrets.RANCHER_SECRET_KEY }}
          RANCHER_URL: https://rancher.broetje.online/v3/project/local:p-sr5th/workloads/deployment:yggdrasil:yggdrasil-node1
          RANCHER_DATA: |
            [
              {
                "name": "yggdrasil-node1",
                "image": "docker.pkg.github.com/tbroetje/dockerfiles/yggdrasil:0.0.1"
              }
            ]
